apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-djangoeks
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-djangoeks
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-djangoeks
    spec:
      serviceAccountName: {{ .Values.django.serviceAccountName | default "default" }}
      containers:
        - name: djangoeks
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DJANGO_SECRET_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_PORT
