apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-djangoeks
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: djangoeks
  template:
    metadata:
      labels:
        app: djangoeks
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: secret_key
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: db_name
