apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-djangoeks
  labels:
    app: {{ .Release.Name }}-djangoeks
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-djangoeks
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-djangoeks
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: djangoeks
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.secretKey }}"
