apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-djangoeks
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-djangoeks
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
