apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-djangoeks
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-djangoeks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
