replicaCount: 2

image:
  repository: 998244281811.dkr.ecr.eu-central-1.amazonaws.com/djangoeks
  tag: v1.0.0

serviceAccount:
  name: django-eks-sa
  create: true        # <-- dodaj to, żeby Helm utworzył SA
  iamRoleArn: ""      # możesz zostawić pusty

ingress:
  host: example.com

# SECRET_KEY zostawiamy pusty placeholder, w pipeline podmienimy go na prawdziwy secret
secretKey: ""
