replicaCount: 2

image:
  repository: 998244281811.dkr.ecr.eu-central-1.amazonaws.com/djangoeks
  tag: latest

serviceAccount:
  name: english-platform-dev
  create: false
  iamRoleArn: arn:aws:iam::998244281811:role/english-platform-dev-role

envSecretName: django-secrets

secretKey: ""

db:
  host: postgresql
  user: ""
  password: ""
  name: ""
  port: "5432"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
    - host: terrautops.org
      paths:
        - path: /
          pathType: Prefix

