name: CI/CD Django EKS

on:
  push:
    branches: [main]

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: 998244281811.dkr.ecr.eu-central-1.amazonaws.com/djangoeks
  K8S_NAMESPACE: platform-app
  HELM_RELEASE_NAME: djangoeks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG platform-app/backend
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Configure kubectl
        run: aws eks update-kubeconfig --name eks-platform --region $AWS_REGION

      - name: Generate secrets values
        run: |
          cat <<EOF > secrets.yaml
envSecretName: django-secrets
secretKey: "${{ secrets.DJANGO_SECRET_KEY }}"

db:
  host: postgresql
  user: "${{ secrets.DB_USER }}"
  password: "${{ secrets.DB_PASSWORD }}"
  name: "${{ secrets.DB_NAME }}"
  port: "5432"
EOF

      - name: Deploy Helm
        run: |
          helm upgrade --install $HELM_RELEASE_NAME platform-app/helm-charts \
            -n $K8S_NAMESPACE \
            --create-namespace \
            -f platform-app/helm-charts/values.yaml \
            -f secrets.yaml \
            --set image.tag=$IMAGE_TAG \
            --wait --timeout 10m
