name: CI/CD Django EKS

on:
  push:
    branches:
      - main
      - staging
      - develop

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: 998244281811.dkr.ecr.eu-central-1.amazonaws.com/djangoeks
  K8S_NAMESPACE: platform-app
  HELM_RELEASE_NAME: djangoeks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2Ô∏è‚É£ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3Ô∏è‚É£ Log in to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4Ô∏è‚É£ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}-${{ github.ref_name }}
          docker build -t "$ECR_REPOSITORY:$IMAGE_TAG" "$GITHUB_WORKSPACE/platform-app/backend"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 5Ô∏è‚É£ Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push "$ECR_REPOSITORY:$IMAGE_TAG"

      # 6Ô∏è‚É£ Configure kubectl for EKS
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name eks-platform --region "$AWS_REGION"

      # 7Ô∏è‚É£ Set Django secret in environment
      - name: Set Django secret
        run: echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV

      # 8Ô∏è‚É£ Deploy to EKS via Helm
      - name: Deploy to EKS via Helm
        run: |
          CHART_PATH="$GITHUB_WORKSPACE/platform-app/helm-charts"
          ls -la $CHART_PATH      # üîπ sprawdza czy katalog istnieje
          helm upgrade --install "$HELM_RELEASE_NAME" "$CHART_PATH" \
            --namespace "$K8S_NAMESPACE" \
            --create-namespace \
            --set image.repository="$ECR_REPOSITORY" \
            --set image.tag="$IMAGE_TAG" \
            --set serviceAccount.name="django-eks-sa" \
            --set ingress.host="example.com" \
            --set-string secretKey="$DJANGO_SECRET_KEY" \
            --timeout 10m \
            --wait \
            --debug
