name: CI/CD Django EKS

on:
  push:
    branches:
      - main
      - staging
      - develop

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: 998244281811.dkr.ecr.eu-central-1.amazonaws.com/djangoeks
  K8S_NAMESPACE: platform-app
  HELM_RELEASE_NAME: djangoeks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Konfiguracja AWS creds
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Logowanie do ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4️⃣ Build obrazu
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}-${{ github.ref_name }}
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG $GITHUB_WORKSPACE/platform-app/backend
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 5️⃣ Push obrazu do ECR
      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      # 6️⃣ Update kubeconfig do EKS
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name eks-platform --region $AWS_REGION

      # 7️⃣ Deploy przez Helm
      - name: Deploy to EKS via Helm
        run: |
          helm upgrade --install $HELM_RELEASE_NAME ./platform-app/helm-charts \
            --namespace $K8S_NAMESPACE \
            --create-namespace \
            --set image.repository=$ECR_REPOSITORY \
            --set image.tag=$IMAGE_TAG \
            --set serviceAccount.name=django-eks-sa \
            --set ingress.host=example.com \
            --set secretKey=${{ secrets.DJANGO_SECRET_KEY }} \
            --timeout 10m \
            --wait
