name: CI/CD Django EKS

on:
  push:
    branches:
      - main
      - staging
      - develop

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: 998244281811.dkr.ecr.eu-central-1.amazonaws.com/djangoeks
  K8S_NAMESPACE: platform-app
  HELM_RELEASE_NAME: djangoeks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}-${{ github.ref_name }}
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG $GITHUB_WORKSPACE/platform-app/backend
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 5️⃣ Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      # 6️⃣ Configure kubectl
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name eks-platform --region $AWS_REGION

# 7️⃣ Generate secrets.yaml dynamically
      - name: Create secrets.yaml
  run: |
    echo "envSecretName: django-secrets" > secrets.yaml
    echo "secretKey: \"${{ secrets.DJANGO_SECRET_KEY }}\"" >> secrets.yaml
    echo "postgres:" >> secrets.yaml
    echo "  host: postgresql" >> secrets.yaml
    echo "  username: \"${{ secrets.DB_USER }}\"" >> secrets.yaml
    echo "  password: \"${{ secrets.DB_PASSWORD }}\"" >> secrets.yaml
    echo "  database: \"${{ secrets.DB_NAME }}\"" >> secrets.yaml
    echo "  port: \"5432\"" >> secrets.yaml
  
    - name: Deploy to EKS via Helm
  run: |
    CHART_PATH=$GITHUB_WORKSPACE/platform-app/helm-charts
    helm upgrade --install $HELM_RELEASE_NAME $CHART_PATH \
      --namespace $K8S_NAMESPACE \
      --create-namespace \
      --values $CHART_PATH/values.yaml \
      --values ./secrets.yaml \
      --set image.repository=$ECR_REPOSITORY \
      --set image.tag=$IMAGE_TAG \
      --set serviceAccount.name="english-platform-dev" \
      --set ingress.host="example.com" \
      --timeout 10m \
      --wait \
      --debug