name: CI/CD Django EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: 998244281811.dkr.ecr.eu-central-1.amazonaws.com/djangoeks
  K8S_NAMESPACE: platform-app
  HELM_RELEASE_NAME: djangoeks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4️⃣ Build & push Docker image
      - name: Build & push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG platform-app/backend
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 5️⃣ Configure kubectl
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name eks-platform --region $AWS_REGION

      # 6️⃣ Generate Helm secrets values
      - name: Generate secrets.yaml
        run: |
          cat > secrets.yaml <<EOF
envSecretName: django-secrets
secretKey: "${{ secrets.DJANGO_SECRET_KEY }}"

postgres:
  host: postgresql
  username: "${{ secrets.DB_USER }}"
  password: "${{ secrets.DB_PASSWORD }}"
  database: "${{ secrets.DB_NAME }}"
  port: "5432"
EOF

      # 7️⃣ Deploy via Helm
      - name: Deploy to EKS via Helm
        run: |
          CHART_PATH="platform-app/helm-charts"
          helm upgrade --install $HELM_RELEASE_NAME $CHART_PATH \
            --namespace $K8S_NAMESPACE \
            --create-namespace \
            -f $CHART_PATH/values.yaml \
            -f ./secrets.yaml \
            --set image.repository=$ECR_REPOSITORY \
            --set image.tag=$IMAGE_TAG \
            --set serviceAccount.name="english-platform-dev" \
            --wait \
            --timeout 10m \
            --debug
